import type { AttendanceRecord } from "./types";

export const ATTENDANCE_MOCK: AttendanceRecord[] = [
  {
    id: "att-001",
    employee: {
      id: "emp-001",
      name: "Sarah Wijaya",
      email: "sarah.wijaya@saasdesk.com",
      avatar: "",
      department: "Marketing",
    },
    date: "2026-10-15",
    clockIn: "08:31",
    clockOut: "05:45",
    status: "Active",
  },
  {
    id: "att-002",
    employee: {
      id: "emp-002",
      name: "Andi Pratama",
      email: "andi.pratama@saasdesk.com",
      avatar: "",
      department: "Product",
    },
    date: "2026-10-15",
    clockIn: "09:12",
    clockOut: "06:10",
    status: "Late",
  },
  {
    id: "att-003",
    employee: {
      id: "emp-003",
      name: "Dewi Lestari",
      email: "dewi.lestari@saasdesk.com",
      avatar: "",
      department: "Product",
    },
    date: "2026-10-15",
    clockIn: null,
    clockOut: null,
    status: "On Leave",
  },
  {
    id: "att-004",
    employee: {
      id: "emp-004",
      name: "Budi Santoso",
      email: "budi.santoso@saasdesk.com",
      avatar: "",
      department: "Engineering",
    },
    date: "2026-10-14",
    clockIn: "08:45",
    clockOut: "05:30",
    status: "Active",
  },
  {
    id: "att-005",
    employee: {
      id: "emp-005",
      name: "Maya Chen",
      email: "maya.chen@saasdesk.com",
      avatar: "",
      department: "Design",
    },
    date: "2026-10-14",
    clockIn: "09:05",
    clockOut: "06:00",
    status: "Late",
  },
  {
    id: "att-006",
    employee: {
      id: "emp-006",
      name: "James Wilson",
      email: "james.wilson@saasdesk.com",
      avatar: "",
      department: "Sales",
    },
    date: "2026-10-13",
    clockIn: null,
    clockOut: null,
    status: "On Leave",
  },
  {
    id: "att-007",
    employee: {
      id: "emp-007",
      name: "Siti Rahayu",
      email: "siti.rahayu@saasdesk.com",
      avatar: "",
      department: "HR",
    },
    date: "2026-10-12",
    clockIn: "08:20",
    clockOut: "05:40",
    status: "Active",
  },
  {
    id: "att-008",
    employee: {
      id: "emp-008",
      name: "Kevin Hartanto",
      email: "kevin.hartanto@saasdesk.com",
      avatar: "",
      department: "Finance",
    },
    date: "2026-10-10",
    clockIn: "09:20",
    clockOut: "06:15",
    status: "Late",
  },
  {
    id: "att-009",
    employee: {
      id: "emp-009",
      name: "Laura Garcia",
      email: "laura.garcia@saasdesk.com",
      avatar: "",
      department: "Engineering",
    },
    date: "2026-10-09",
    clockIn: "08:55",
    clockOut: "05:50",
    status: "Active",
  },
  {
    id: "att-010",
    employee: {
      id: "emp-010",
      name: "Ahmad Fauzi",
      email: "ahmad.fauzi@saasdesk.com",
      avatar: "",
      department: "Operations",
    },
    date: "2026-10-08",
    clockIn: null,
    clockOut: null,
    status: "On Leave",
  },
  {
    id: "att-011",
    employee: {
      id: "emp-011",
      name: "Grace Kim",
      email: "grace.kim@saasdesk.com",
      avatar: "",
      department: "Customer Support",
    },
    date: "2026-10-05",
    clockIn: "08:15",
    clockOut: "05:35",
    status: "Active",
  },
  {
    id: "att-012",
    employee: {
      id: "emp-012",
      name: "David Lee",
      email: "david.lee@saasdesk.com",
      avatar: "",
      department: "Data",
    },
    date: "2026-10-01",
    clockIn: "09:30",
    clockOut: "06:20",
    status: "Late",
  },
];
